name: Generate Release on Merge

on:
  push:
    branches:
      - main

jobs:
  generate-release:
    name: Generate Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Check
        run: deno lint

      - name: Format Check
        run: deno fmt --check

      - name: Execute Tests
        run: deno task test

      - uses: funnylookinhat/action-deno-conventional-release@0.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
